#!/bin/sh

teal_compile() { \
	cat >> $2 << EOF
<div id="main">
EOF
	$MDC $1 >> $2
cat >> $2 << EOF
</div>
EOF

	echo "MDC $1 >> $2"
}

teal_head() { \
	name=$(echo $1 | sed 's/.html//' | awk -F"/" '{OFS="/"; print $NF}')
	cat > $1 << EOF
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/png" href="/favicon.png" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Language" content="en" />
<meta content="width=device-width" name="viewport" />
<meta content="$KEYWORDS" name="keywords" />
<meta content="$DESCRIPTION" name="description" />
<title>$name - $TITLE</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
EOF
	echo "HTMLINFO $1"
}

teal_sidebar() { \
cat >> $1 << EOF
<div id="side-bar">
<span>
<a href="index.html">home</a>
EOF
	for f in $EXTRA_PAGES; do
		cat >> $1 << EOF
<a href="$f.html">$f</a>
EOF
	done
	for file in $(find "$SRC" | grep ".md" | sed "/index.md/d;/^$/d" | sort); do
		cat >> $1 << EOF
<a href="$(echo $file | sed "s,$SRC/,,;s/\.md/\.html/")">$(echo $file | sed "s,$SRC/,,;s/.md//")</a>
EOF
	done
cat >> $1 << EOF
</span>
</div>
</div>
EOF
}

teal_header() { \
	cat >> $1 << EOF
<div id="header">
<span>
<img src="/favicon.png">
<h1>$TITLE</h1>
</span>
EOF
}

teal_footer() { \
	cat >> $1 << EOF
<div id="footer">
<p>$FOOTER</p>
</div>
EOF
}

teal_end() { \
	cat >> $1 << EOF
</body>
</html>
EOF
}

teal_loop() { \
	# copy all necessary files from source dir to target dir
	mkdir -p $TARGET
	cp -rf $SRC/* $TARGET
	cp -f style.css $TARGET

	# remove the source files
	for f in $(find $TARGET | grep .md); do
		rm -f $f
	done

	for f in $(find $SRC | grep .md); do
		out="$TARGET/$(echo $f | sed "s/\.md/\.html/;s,$SRC/,,;/^$/d")"
		teal_head $out
		teal_header $out
		teal_sidebar $out
		teal_compile $f $out
		teal_footer $out
		teal_end $out
	done
}


[ ! -f "teal.conf" ] && echo "no teal.conf found! must abort." && exit 1
[ ! -f "style.css" ] && echo "no style.css found! must abort." && exit 1

. ./teal.conf
teal_loop
