#!/bin/sh

# compile webpage content from markdown to html
teal_compile() {
	cat >> $2 << EOF
<div id="wrapper">
EOF
	$MDC $1 >> $2
cat >> $2 << EOF
</div>
EOF

	echo "MDC $1 >> $2"
}

# print beginning section of html (before main content and sidebar)
teal_head() {
	. $2
	[ "$1" = "$TARGET/index.html" ] && NAME="$TITLE"
	cp $HEADFILE $1
	echo "HTMLINFO $1"
}

# generate link menu
teal_sidebar() {
	cat >> $1 << EOF
<div id="side-bar">
<span>
EOF
	[ ! -z "$SIDEBAR_SOURCES" ] && for file in $(echo $SIDEBAR_SOURCES | tr ' ' '\n' | sed "s|^|$SRC/|"); do
		. $(echo $file | sed 's/md$/sh/')
		cat >> $1 << EOF
<a href="$(echo $file | sed "s,$SRC/,,;s/\.md/\.html/")">$NAME</a>
EOF
	done
	for ep in $EXTRA_PAGES; do
		cat >> $1 << EOF
<a href="$(echo $ep | sed 's/,.*$//')">$(echo $ep | sed 's/.*,//')</a>
EOF
	done
	cat >> $1 << EOF
</span>
</div>
</span>
</div>
EOF
}

teal_footer() {
	cat >> $1 << EOF
<div id="footer">
<p>$FOOTER</p>
</div>
EOF
}

teal_end() {
	cat >> $1 << EOF
</body>
</html>
EOF
}

teal_loop() {
	# copy all necessary files from source dir to target dir
	mkdir -p $TARGET
	cp -rf $SRC/* $TARGET
	cp -f style.css $TARGET

	# remove the source files
	for f in $(find $TARGET | grep -E '(md)|(sh)$'); do
		rm -f $f
	done

	for f in $SOURCES; do
		settings="$SRC/$(echo $f | sed "s/\.md/\.sh/;/^$/d")"
		out="$TARGET/$(echo $f | sed "s/\.md/\.html/;/^$/d")"
		teal_head $out $settings
		teal_sidebar $out
		teal_compile "$SRC/$f" $out
		[ ! -z "$FOOTER" ] && teal_footer $out
		teal_end $out $settings
	done
}


[ ! -f "teal.conf" ] && echo "no teal.conf found! must abort." && exit 1
[ ! -f "style.css" ] && echo "no style.css found! must abort." && exit 1

. ./teal.conf
teal_loop
